// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-aIAeJZx5nqnyV3kuAjKmP5PuFCbbuAI',
    appId: '1:558285690472:web:4eb38ebf54bdc5437a0ddd',
    messagingSenderId: '558285690472',
    projectId: 'jo-market-c8792',
    authDomain: 'jo-market-c8792.firebaseapp.com',
    storageBucket: 'jo-market-c8792.firebasestorage.app',
    measurementId: 'G-DY2QM61F22',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuwaDCYopJKx7GfOHXPC0GbxGwVyaHFs',
    appId: '1:558285690472:ios:dd584608590938c17a0ddd',
    messagingSenderId: '558285690472',
    projectId: 'jo-market-c8792',
    storageBucket: 'jo-market-c8792.firebasestorage.app',
    iosBundleId: 'com.example.finalPrject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcloWZSlbF8Iarf5X-xyFkGjgskHEPyMo',
    appId: '1:558285690472:android:4acd66535e319d607a0ddd',
    messagingSenderId: '558285690472',
    projectId: 'jo-market-c8792',
    storageBucket: 'jo-market-c8792.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-aIAeJZx5nqnyV3kuAjKmP5PuFCbbuAI',
    appId: '1:558285690472:web:4b2b9260ab17b8317a0ddd',
    messagingSenderId: '558285690472',
    projectId: 'jo-market-c8792',
    authDomain: 'jo-market-c8792.firebaseapp.com',
    storageBucket: 'jo-market-c8792.firebasestorage.app',
    measurementId: 'G-Z327CK14J6',
  );

}